// src/components/GfxPreview.tsx
import type { CSSProperties } from "react";
import { cn } from "../utils/cn";
import { fa } from "../lib/format";
import { Gamepad } from "./Icons";

export type Quality = "low" | "mid" | "high" | "ultra";

const Q_LABEL: Record<Quality, string> = {
  low: "پایین",
  mid: "متوسط",
  high: "بالا",
  ultra: "اولترا",
};

const FACES = [
  "translateZ(64px)",
  "rotateY(180deg) translateZ(64px)",
  "rotateY(90deg) translateZ(64px)",
  "rotateY(-90deg) translateZ(64px)",
  "rotateX(90deg) translateZ(64px)",
  "rotateX(-90deg) translateZ(64px)",
];

const PARTS = [
  { l: 12, t: 20, s: 4, c: "#ffb44d", d: 0 },
  { l: 82, t: 16, s: 3, c: "#3fd8bb", d: 0.6 },
  { l: 18, t: 72, s: 3, c: "#6cbcff", d: 1.1 },
  { l: 76, t: 68, s: 4, c: "#ffb44d", d: 0.3 },
  { l: 46, t: 8, s: 3, c: "#ffcf82", d: 1.6 },
  { l: 92, t: 44, s: 3, c: "#3fd8bb", d: 0.9 },
  { l: 6, t: 46, s: 4, c: "#ff7a66", d: 1.9 },
  { l: 62, t: 86, s: 3, c: "#6cbcff", d: 0.4 },
  { l: 30, t: 34, s: 2, c: "#8beedd", d: 2.2 },
  { l: 68, t: 30, s: 2, c: "#ffcf82", d: 1.3 },
  { l: 88, t: 80, s: 3, c: "#ffb44d", d: 2.5 },
  { l: 8, t: 86, s: 3, c: "#3fd8bb", d: 0.8 },
  { l: 52, t: 92, s: 2, c: "#ff7a66", d: 1.7 },
  { l: 38, t: 58, s: 2, c: "#a8d8ff", d: 2.8 },
];

/** پیش‌نمایش زنده — مکعب سه‌بعدی که به کیفیت و نرخ فریم واکنش نشان می‌دهد */
export function GfxPreview({
  quality,
  fps,
  vsync,
}: {
  quality: Quality;
  fps: number;
  vsync: boolean;
}) {
  const qIdx = (["low", "mid", "high", "ultra"] as Quality[]).indexOf(quality);
  const effFps = vsync ? Math.min(fps, 60) : fps;
  const dur = Math.max(2.4, 9 - effFps / 30);
  const particleCount = [0, 5, 9, 14][qIdx];
  const detail = [0.06, 0.22, 0.5, 0.95][qIdx];
  const iconOp = [0, 0, 0.4, 0.85][qIdx];
  const filter =
    qIdx === 0 ? "saturate(0.55) blur(0.6px)" : qIdx === 1 ? "saturate(0.85)" : "none";
  const glow =
    qIdx === 3
      ? "0 0 70px rgba(255,154,31,0.22), inset 0 0 60px rgba(255,154,31,0.04)"
      : qIdx === 2
        ? "0 0 50px rgba(63,216,187,0.12)"
        : "none";

  return (
    <div className="relative flex h-full min-h-[340px] flex-col overflow-hidden rounded-[20px] border border-line bg-gradient-to-b from-ink-900 to-ink-950 p-6">
      <div
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(360px 230px at 50% 42%, rgba(255,154,31,0.09), transparent 65%)",
        }}
      />

      <div className="relative flex items-center justify-between">
        <p className="text-[13px] font-medium text-mist">پیش‌نمایش زنده موتور</p>
        <span className="flex items-center gap-1.5 rounded-full border border-jade-500/30 bg-jade-500/10 px-2.5 py-1 font-tech text-[10px] tracking-widest text-jade-300">
          <span
            className="h-1.5 w-1.5 rounded-full bg-jade-400"
            style={{ animation: "kf-blink 2s ease-in-out infinite" }}
          />
          REALTIME
        </span>
      </div>

      {/* صحنه سه‌بعدی */}
      <div
        className="cube-stage relative mx-auto my-auto grid h-[220px] w-[220px] place-items-center rounded-full transition-shadow duration-700"
        style={{ "--face-detail": detail, boxShadow: glow } as CSSProperties}
      >
        {PARTS.slice(0, particleCount).map((p, i) => (
          <span
            key={i}
            className="absolute rounded-full"
            style={{
              left: `${p.l}%`,
              top: `${p.t}%`,
              width: p.s,
              height: p.s,
              background: p.c,
              boxShadow: `0 0 ${p.s * 2.5}px ${p.c}`,
              animation: `kf-float ${4.5 + (i % 5)}s ease-in-out ${p.d}s infinite`,
            }}
          />
        ))}

        <div
          className="cube relative h-[128px] w-[128px] transition-[filter] duration-700"
          style={{ "--cube-dur": `${dur.toFixed(2)}s`, filter } as CSSProperties}
        >
          {FACES.map((t) => (
            <div key={t} className="cube-face" style={{ transform: t }}>
              <Gamepad
                className="absolute left-1/2 top-1/2 h-10 w-10 -translate-x-1/2 -translate-y-1/2 text-ember-300 transition-opacity duration-500"
                style={{ opacity: iconOp }}
              />
            </div>
          ))}
        </div>

        <div className="absolute bottom-3 left-1/2 h-5 w-32 -translate-x-1/2 rounded-full bg-black/60 blur-md" />
      </div>

      {/* قرائت‌ها */}
      <div className="relative grid grid-cols-3 gap-2.5">
        <div className="rounded-xl border border-line bg-ink-850/80 px-3 py-2.5 text-center">
          <p className="font-tech text-xl font-bold leading-7 text-jade-300">{fa(effFps)}</p>
          <p className="text-[10.5px] text-dim">FPS</p>
        </div>
        <div className="rounded-xl border border-line bg-ink-850/80 px-3 py-2.5 text-center">
          <p className="text-lg font-bold leading-7 text-ember-300">{Q_LABEL[quality]}</p>
          <p className="text-[10.5px] text-dim">کیفیت</p>
        </div>
        <div className="rounded-xl border border-line bg-ink-850/80 px-3 py-2.5 text-center">
          <p
            className={cn(
              "text-lg font-bold leading-7",
              vsync ? "text-jade-300" : "text-dim"
            )}
          >
            {vsync ? "فعال" : "غیرفعال"}
          </p>
          <p className="text-[10.5px] text-dim">V-SYNC</p>
        </div>
      </div>

      {vsync && fps > 60 && (
        <p className="relative mt-2.5 text-center text-[11px] text-dim">
          V-Sync نرخ فریم را روی {fa(60)} قفل می‌کند
        </p>
      )}
    </div>
  );
}

// resources/js/Components/Settings/GfxPreview.vue
<script setup>
/**
 * GfxPreview — پیش‌نمایش زندهٔ موتور گرافیک
 * مسیر: resources/js/Components/Settings/GfxPreview.vue
 *
 * مکعب سه‌بعدی واقعاً به تنظیمات واکنش نشان می‌دهد:
 *   • سرعت چرخش  ← نرخ فریم مؤثر
 *   • جزئیات وجوه، ذرات و هاله ← کیفیت بافت
 *   • V-Sync ← قفل شدن فریم روی ۶۰
 * از کلاس‌های a3d-cube/a3d-cube__face موجود در archive-3d.css استفاده می‌کند.
 */
import { computed } from 'vue'
import { Gamepad2 } from 'lucide-vue-next'
import { faInt } from '@/Utils/format'

const props = defineProps({
    /** 'low' | 'mid' | 'high' | 'ultra' */
    quality: { type: String, default: 'high' },
    fps: { type: Number, default: 144 },
    vsync: { type: Boolean, default: true },
})

const LEVELS = ['low', 'mid', 'high', 'ultra']
const LABELS = { low: 'پایین', mid: 'متوسط', high: 'بالا', ultra: 'اولترا' }

const FACES = [
    'front',
    'back',
    'right',
    'left',
    'top',
    'bottom',
]

const PARTICLES = [
    { l: 12, t: 20, s: 4, c: 'var(--gs-gold)', d: 0 },
    { l: 82, t: 16, s: 3, c: 'var(--gs-accent-2)', d: 0.6 },
    { l: 18, t: 72, s: 3, c: 'var(--gs-accent)', d: 1.1 },
    { l: 76, t: 68, s: 4, c: 'var(--gs-gold-light)', d: 0.3 },
    { l: 46, t: 8, s: 3, c: 'var(--gs-gold)', d: 1.6 },
    { l: 92, t: 44, s: 3, c: 'var(--gs-accent-2)', d: 0.9 },
    { l: 6, t: 46, s: 4, c: 'var(--gs-accent-3)', d: 1.9 },
    { l: 62, t: 86, s: 3, c: 'var(--gs-accent)', d: 0.4 },
    { l: 30, t: 34, s: 2, c: 'var(--gs-gold-light)', d: 2.2 },
    { l: 68, t: 30, s: 2, c: 'var(--gs-gold)', d: 1.3 },
    { l: 88, t: 80, s: 3, c: 'var(--gs-accent-3)', d: 2.5 },
    { l: 8, t: 86, s: 3, c: 'var(--gs-accent-2)', d: 0.8 },
    { l: 52, t: 92, s: 2, c: 'var(--gs-accent)', d: 1.7 },
    { l: 38, t: 58, s: 2, c: 'var(--gs-gold-light)', d: 2.8 },
]

const level = computed(() => Math.max(0, LEVELS.indexOf(props.quality)))

/** نرخ فریم مؤثر — V-Sync سقف را روی ۶۰ قفل می‌کند */
const effectiveFps = computed(() => (props.vsync ? Math.min(props.fps, 60) : props.fps))

/** هرچه فریم بالاتر، چرخش سریع‌تر (حداقل ۲٫۴ ثانیه) */
const spinDuration = computed(() => Math.max(2.4, 9 - effectiveFps.value / 30))

const particles = computed(() => PARTICLES.slice(0, [0, 5, 9, 14][level.value]))

const cubeStyle = computed(() => ({
    animationDuration: `${spinDuration.value.toFixed(2)}s`,
    filter:
        level.value === 0
            ? 'saturate(0.5) blur(0.7px)'
            : level.value === 1
              ? 'saturate(0.85)'
              : 'none',
}))

const stageStyle = computed(() => ({
    boxShadow:
        level.value === 3
            ? '0 0 80px var(--gs-gold-glow)'
            : level.value === 2
              ? '0 0 50px rgba(91, 157, 240, 0.12)'
              : 'none',
}))

/** شفافیت آیکون روی وجوه — در کیفیت پایین دیده نمی‌شود */
const iconOpacity = computed(() => [0, 0, 0.42, 0.9][level.value])

const qualityLabel = computed(() => LABELS[props.quality] || '—')
</script>

<template>
    <div class="a3d-holo st-gfx">
        <div class="st-gfx__topbar">
            <span class="st-gfx__caption">پیش‌نمایش زندهٔ موتور</span>
            <span class="st-chip st-chip--live">
                <span class="st-dot" />
                REALTIME
            </span>
        </div>

        <!-- صحنهٔ سه‌بعدی -->
        <div class="st-gfx__stage" :style="stageStyle">
            <!-- ذرات محیطی؛ تعدادشان با کیفیت زیاد می‌شود -->
            <TransitionGroup name="st-particle">
                <span
                    v-for="(p, i) in particles"
                    :key="`${p.l}-${p.t}`"
                    class="st-gfx__particle"
                    :style="{
                        left: `${p.l}%`,
                        top: `${p.t}%`,
                        width: `${p.s}px`,
                        height: `${p.s}px`,
                        background: p.c,
                        boxShadow: `0 0 ${p.s * 2.5}px ${p.c}`,
                        animationDuration: `${4.5 + (i % 5)}s`,
                        animationDelay: `${p.d}s`,
                    }"
                />
            </TransitionGroup>

            <div class="a3d-cube st-gfx__cube" :style="cubeStyle">
                <div
                    v-for="face in FACES"
                    :key="face"
                    class="a3d-cube__face"
                    :class="`a3d-cube__face--${face}`"
                >
                    <Gamepad2
                        :size="34"
                        :style="{ opacity: iconOpacity, transition: 'opacity 0.5s ease' }"
                    />
                </div>
            </div>

            <span class="st-gfx__shadow" />
        </div>

        <!-- قرائت‌های زنده -->
        <div class="st-gfx__readouts">
            <div class="st-gfx__cell">
                <p class="st-gfx__val st-gfx__val--green">{{ faInt(effectiveFps) }}</p>
                <p class="st-gfx__key">FPS</p>
            </div>
            <div class="st-gfx__cell">
                <p class="st-gfx__val">{{ qualityLabel }}</p>
                <p class="st-gfx__key">کیفیت</p>
            </div>
            <div class="st-gfx__cell">
                <p
                    class="st-gfx__val"
                    :class="vsync ? 'st-gfx__val--green' : 'st-gfx__val--off'"
                >
                    {{ vsync ? 'فعال' : 'خاموش' }}
                </p>
                <p class="st-gfx__key">V-SYNC</p>
            </div>
        </div>

        <p v-if="vsync && fps > 60" class="st-gfx__note">
            V-Sync نرخ فریم را روی ۶۰ قفل می‌کند
        </p>
    </div>
</template>

<style scoped>
.st-gfx__topbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.6rem;
}

.st-gfx__caption {
    font-size: 0.76rem;
    color: var(--gs-text-secondary);
}

.st-gfx__cube {
    --cube-size: 126px;
}

.st-gfx__particle {
    position: absolute;
    border-radius: 50%;
    animation-name: st-float;
    animation-timing-function: ease-in-out;
    animation-iteration-count: infinite;
    pointer-events: none;
}

.st-gfx__note {
    margin-top: 0.55rem;
    text-align: center;
    font-size: 0.7rem;
    color: var(--gs-text-muted);
}

.st-particle-enter-active,
.st-particle-leave-active {
    transition: opacity 0.5s ease, transform 0.5s cubic-bezier(0.34, 1.56, 0.64, 1);
}
.st-particle-enter-from,
.st-particle-leave-to {
    opacity: 0;
    transform: scale(0);
}
</style>
